aws_access_key_id: "changeme"
aws_secret_access_key: "changeme"
aws_base_domain: archidep-2018.media
aws_image: ami-0ac019f4fcb7cb7e6
aws_instance_type: t3.small
aws_key_name: ArchiDep
aws_region: eu-west-1
aws_security_group: sg-changeme
aws_subnet: subnet-changeme
smtp_address: no-reply@example.com
smtp_host: mail.example.com
smtp_port: 465
smtp_secure: true
smtp_username: no-reply@example.com
smtp_password: "changeme"
